---
title: "HD Rmd template"
author: "Holger Doering --- holger.doering@gesis.org"
date: "`r format(Sys.time(), '%d %B %Y, %H:%M')`"
output:
  html_document:
    df_print: paged
    code_folding: hide
    toc: yes
    toc_float: yes
  html_notebook:
    code_folding: hide
    toc: yes
    toc_float: yes
---
<style type="text/css"> <!-- .table { width: auto } ---> </style>

```{r options, include=FALSE}
knitr::opts_knit$set(
  # results = "hide",
  # comment = NA,
  message = FALSE,
  warning = FALSE,
  package.startup.message = FALSE
  # # some options not used in "html_notebook" preview
  )

options(
  tidyverse.quiet = TRUE,
  dplyr.summarise.inform = FALSE,
  readr.num_columns = 0,
  knitr.kable.NA = "",
  width = 100
)
```


```{r corepacks}
library(broom)      # models // tidy results
library(ggeffects)  # models // visualize model effects
library(patchwork)  # plots  // arrange
library(reactable)  # layout // interactive data tables

library(knitr)      # layout // tables in RMarkdown with kable()
library(tidyverse)  # —      // load last to avoid masking
# skimr::           # packages // used (once) but not loaded

ggplot2::theme_set(theme_minimal())

round_numeric_variables <- function(data, digits = 0) {
  data |> mutate(across(where(is.numeric), \(x) round(x, digits)))
  }
```

_Note_ -- see [Quarto](https://quarto.org/docs/guide/) and use it potentially instead of [R Markdown](https://rmarkdown.rstudio.com/lesson-1.html)

---

<https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/mtcars.html>


## Summary data

```{r data}
mtcars_raw <- as_tibble(datasets::mtcars)
```


```{r check, eval=FALSE}
glimpse(mtcars)
summary(mtcars)
```


```{r skim}
mtcars_raw |> 
  skimr::skim() |> 
  select(-matches("numeric\\.p.5"), -skim_type, -complete_rate) |> 
  rename_with(~ str_remove(.x, "^skim_|^n_|^numeric\\.")) |> 
  round_numeric_variables(1) |> 
  knit_print()
```

```{r figure, message=FALSE}
pl_dt <- 
  mtcars_raw |> 
  mutate(cyl = forcats::as_factor(cyl))

pl1 <- ggplot(pl_dt, aes(x=hp, y=mpg, color=cyl, shape=cyl)) +
  geom_point(size=3)

pl2 <- ggplot(pl_dt, aes(x=hp, y=mpg)) +
  geom_point(alpha=0.5) +
  geom_smooth(se = FALSE)

pl1 + pl2
```


## Linear model

```{r}
m1 <- lm(mpg ~ log(hp), data = mtcars_raw)

tidy(m1) |> kable(digits = 2)
glance(m1) |> kable(digits = 2)

ggpredict(m1, terms = "hp") |> plot()
```

## Explore data

_Note_ -- may only work in HTML documents (Knit to HTML) and not in Notebooks (Preview)

```{r explore}
mtcars_raw |> 
  select(mpg, hp, cyl, gear) |> 
  reactable(searchable = TRUE)
```
